
# security

apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloapp
  labels:
    service: helloapp
    component: web
    team: infrastructure-team
    criticality: low
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      service: helloapp
      component: web
  strategy:
    rollingUpdate:
      maxSurge: 80%
      maxUnavailable: 80%
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      labels:
        service: helloapp
        component: web
        team: infrastructure-team
        criticality: low
        version: v1
    spec:
      automountServiceAccountToken: false
      containers:
      - image: quay.io/alexey_medvedchikov/helloapp:latest
        name: helloapp
        args:
          - "-net.listen=:8080"
          - "-config.path=/etc/helloapp/config.json"
        envFrom:
          - secretRef:
              name: helloapp-env
              optional: false
        resources:
          limits:
            cpu: 200m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: true
          runAsGroup: 1001
          runAsUser: 1001
          runAsNonRoot: true
          capabilities:
            drop:
              - ALL
        ports:
          - name: http
            protocol: TCP
            containerPort: 8080
        livenessProbe:
          httpGet:
            port: http
            path: /
          periodSeconds: 5
          failureThreshold: 3
          successThreshold: 1
          timeoutSeconds: 5
          initialDelaySeconds: 2
        readinessProbe:
          httpGet:
            port: http
            path: /
          periodSeconds: 2
          failureThreshold: 2
          successThreshold: 3
          timeoutSeconds: 3
          initialDelaySeconds: 2
        volumeMounts:
          - mountPath: /etc/helloapp
            name: config
            readOnly: true
      volumes:
        - name: config
          configMap:
            name: helloapp
            optional: false
            defaultMode: 0555

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: helloapp
  labels:
    service: helloapp
    component: web
    team: infrastructure-team
    criticality: low
    version: v1
data:
  config.json: |
    {
      "text_to_show": "Hello, Scala!"
    }

---

apiVersion: v1
kind: Secret
metadata:
  name: helloapp-env
  labels:
    service: helloapp
    component: web
    team: infrastructure-team
    criticality: low
    version: v1
type: Opaque
data:
  DB_DSN: "cG9zdGdyZXNxbDovL2hlbGxvYXBwOm15cGFzc3dvcmRAMTAuMTAuMTAuMTAvaGVsbG9hcHA="

---

apiVersion: v1
kind: Service
metadata:
  name: helloapp
  labels:
    service: helloapp
    component: web
    team: infrastructure-team
    criticality: low
    version: v1
spec:
  type: ClusterIP
  selector:
    service: helloapp
    component: web
  ports:
    - port: 80
      targetPort: http
      name: http
      protocol: TCP

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: helloapp
  labels:
    service: helloapp
    component: web
    team: infrastructure-team
    criticality: low
    version: v1
spec:
  rules:
    - host: helloapp.io
      http:
        paths:
          - backend:
              serviceName: helloapp
              servicePort: http
            path: /

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: helloapp
  labels:
    service: helloapp
    component: web
    team: infrastructure-team
    criticality: low
    version: v1
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: helloapp
  minReplicas: 4
  maxReplicas: 40
  targetCPUUtilizationPercentage: 90
